"""Periodic table data.

Every lookup accepts an atomic number (`int`) or a case-insensitive symbol
(`str`). The data is generated by ``scripts/elements-data.py``.
"""

import json
from dataclasses import dataclass
from pathlib import Path

from .exc import ElementNotFoundError

__all__ = [
    "Element",
    "bonding_capacity",
    "covalent_radius",
    "electronegativity",
    "from_key",
    "group",
    "is_metal",
    "mass",
    "mass_number",
    "number",
    "period",
    "shell_capacity",
    "symbol",
    "valence",
]


@dataclass(frozen=True, slots=True)
class Element:
    """Chemical element.

    Attributes:
        Z: Atomic number.
        A: Mass number.
        group: Group number, or `None` for lanthanides and actinides.
        period: Period number.
        symbol: Chemical symbol.
        mass: Atomic mass.
        covalent_radius: Pyykko covalent radius, in Angstroms.
        valence: Number of valence electrons.
        electronegativity: Pauling electronegativity, if defined.
        metal: Whether the element is a metal.
    """

    Z: int
    A: int
    group: int | None
    period: int
    symbol: str
    mass: float
    covalent_radius: float
    valence: int
    electronegativity: float | None
    metal: bool


def _load_elements() -> list[Element]:
    path = Path(__file__).with_name("elements-data.json")
    with path.open() as f:
        return [Element(**data) for data in json.load(f)]


_ELEMENTS = _load_elements()
_ELEMENT_BY_NUMBER = {e.Z: e for e in _ELEMENTS}
_ELEMENT_BY_SYMBOL = {e.symbol.casefold(): e for e in _ELEMENTS}

_PERIOD_SHELL_CAPACITY = {1: 2, 2: 8, 3: 8, 4: 18, 5: 18, 6: 32, 7: 32}


def from_key(key: int | str) -> Element:
    """Look up an element.

    Args:
        key: Atomic number or symbol.

    Returns:
        The element.

    Raises:
        TypeError: If `key` is not an `int` or `str`.
        ElementNotFoundError: If no element matches `key`.
    """
    if isinstance(key, int):
        if key not in _ELEMENT_BY_NUMBER:
            msg = f"No element with atomic number {key!r}."
            raise ElementNotFoundError(msg)
        return _ELEMENT_BY_NUMBER[key]

    if isinstance(key, str):
        symb = key.casefold()
        if symb not in _ELEMENT_BY_SYMBOL:
            msg = f"No element with symbol {key!r}."
            raise ElementNotFoundError(msg)
        return _ELEMENT_BY_SYMBOL[symb]

    msg = f"Element key must be int or str, got {type(key).__name__}"
    raise TypeError(msg)


def number(key: int | str) -> int:
    """Get the atomic number.

    Args:
        key: Atomic number or symbol.

    Returns:
        Atomic number.
    """
    return from_key(key).Z


def mass_number(key: int | str) -> int:
    """Get the mass number.

    Args:
        key: Atomic number or symbol.

    Returns:
        Mass number.
    """
    return from_key(key).A


def symbol(key: int | str) -> str:
    """Get the canonical symbol, e.g. ``"Cl"`` for ``"cl"`` or ``17``.

    Args:
        key: Atomic number or symbol.

    Returns:
        Atomic symbol.
    """
    return from_key(key).symbol


def mass(key: int | str) -> float:
    """Get the atomic mass.

    Args:
        key: Atomic number or symbol.

    Returns:
        Atomic mass.
    """
    return from_key(key).mass


def covalent_radius(key: int | str) -> float:
    """Get the Pyykko covalent radius.

    Args:
        key: Atomic number or symbol.

    Returns:
        Covalent radius, in Angstroms.
    """
    return from_key(key).covalent_radius


def group(key: int | str) -> int | None:
    """Get the group number.

    Args:
        key: Atomic number or symbol.

    Returns:
        Group number, or `None` for lanthanides and actinides.
    """
    return from_key(key).group


def period(key: int | str) -> int:
    """Get the period number.

    Args:
        key: Atomic number or symbol.

    Returns:
        Period number.
    """
    return from_key(key).period


def electronegativity(key: int | str) -> float | None:
    """Get the Pauling electronegativity.

    Args:
        key: Atomic number or symbol.

    Returns:
        Pauling electronegativity, or `None` if undefined (e.g. He, Ne, Ar).
    """
    return from_key(key).electronegativity


def is_metal(key: int | str) -> bool:
    """Check whether an element is a metal.

    Args:
        key: Atomic number or symbol.

    Returns:
        `True` for alkali, alkaline earth, poor, and transition metals,
        lanthanides, and actinides.
    """
    return from_key(key).metal


def shell_capacity(key: int | str) -> int:
    """Get the valence shell capacity of the element's period.

    Args:
        key: Atomic number or symbol.

    Returns:
        Shell capacity (2, 8, 18, or 32).
    """
    return _PERIOD_SHELL_CAPACITY[period(key)]


def valence(key: int | str, *, override: dict[str, int] | None = None) -> int:
    """Get the number of valence electrons.

    Args:
        key: Atomic number or symbol.
        override: Valence overrides by symbol.

    Returns:
        Number of valence electrons.
    """
    elem = from_key(key)
    if override is not None and elem.symbol in override:
        return override[elem.symbol]
    return elem.valence


def bonding_capacity(key: int | str, *, override: dict[str, int] | None = None) -> int:
    """Get the bonding capacity, ``min(valence, shell_capacity - valence)``.

    Args:
        key: Atomic number or symbol.
        override: Bonding capacity overrides by symbol.

    Returns:
        Bonding capacity.
    """
    elem = from_key(key)
    if override is not None and elem.symbol in override:
        return override[elem.symbol]
    nval = elem.valence
    return min(nval, _PERIOD_SHELL_CAPACITY[elem.period] - nval)
